---
site:
  title: Chaos Engine
  start_page: chaos-engine::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: content
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v2.0.4/ui-bundle.zip
asciidoc:
  attributes:
    experimental: true
    stem: latexmath
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    source-language: asciidoc@
    tabs: tabs
  extensions:
    - ./content/lib/tabs-block.js
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
